### ISSUE TITLE
Pali Word Spelling Fixes

### ISSUE THREAD

**Issue by deobald** [pariyatti/kosa2#8]
upādānanirodhā — upādāna + nirodha = clinging, attachment, grasping + destruction, cessation, annihilation – a synonym for nibbāna

upādānanirodhā>> upādānanirodha (last 'ā' needs to be an 'a')

- [x] fix in source TXT files
- [x] re-run Kosa2 ingester

**Comment by balwa** [comment]
./bin/kosa-clean-txt-files.sh
./bin/kosa-clone-txt-files.sh

docker-compose -f docker-compose-production.yml build --no-cache

docker-compose -f docker-compose-production.yml down

docker-compose -f docker-compose-production.yml up -d

Running kosa:txt:ingest
Ingesting TXT files in [production]... (this will take a few minutes)

Ingesting Looped Pali Word...

Looped Pali Word TXT: started ingesting file 'txt/pali/pali_words_one_loop_eng.txt' for lang 'eng'
................................................................................................................................................................................................................................................................................................................................................................................................................
Looped Pali Word TXT: started ingesting file 'txt/pali/pali_words_one_loop_por.txt' for lang 'por'
................................................................................................................................................................................................................................................................................................................................................................................................................
Done Looped Pali Word.
